### ISSUE TITLE
pine64-pinephone-charging will not boot

### ISSUE THREAD

**Issue by knuxyl** [dreemurrs-embedded/Jumpdrive#62] opened 2021-10-04 07:28 UTC
The charging version will not boot but the regular version will. It will just keep flashing the LED notification, but nothing else. Nothing in dmesg. Is this image solely for charging the device? If so, can the README please be updated to reflect this? Thanks

**Comment by Danct12** [comment] 2021-10-04 15:05
The purpose of this image is explained here: https://github.com/dreemurrs-embedded/Jumpdrive/issues/55#issuecomment-885978525

Might be a duplicate of #55.

**Closed by Danct12** 2021-10-04 15:05 UTC
